import { SignInButton, SignUpButton, useUser } from "@clerk/nextjs";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  
  const user  = useUser();


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main className={styles.main}>
        <div className={styles.container}>
          <div>
          {!!user.isSignedIn&&<SignInButton/>}
          {!user.isSignedIn&&<SignUpButton/>}</div>
          
        </div>
      </main>
    </>
  );
};

export default Home;
